#!/bin/bash

# Write ~/.gitconfig from the tracked template plus this machine's identity.
#
# git/.gitconfig in this repository is the shared part: core settings, colours,
# push/pull behaviour, diff and merge options, and the alias list. It holds no
# [user] section, because name, email and signing key are per machine.
#
# This script writes the composed result to ~/.gitconfig. It deliberately does
# NOT write back into the repository. An earlier version pointed its output at
# git/.gitconfig and rebuilt a reduced config from a heredoc, which overwrote
# the tracked template and silently dropped roughly half of it -- the same
# mistake setup-ssh-keys.sh used to make with ~/.ssh/config.
#
# deploy-dotfiles.sh does not stow .gitconfig for the same reason: the live
# file is generated, not symlinked.
#
# Usage:
#   ./configure-git-user.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/common.sh"

log_info "Configuring Git user settings..."

# Load environment variables
ENV_FILE="${SCRIPT_DIR}/../env/.env-install"
if [ -f "$ENV_FILE" ]; then
    source "$ENV_FILE"
else
    log_error ".env-install file not found at $ENV_FILE"
    exit 1
fi

if [ -z "${GIT_USER_NAME:-}" ]; then
    log_error "GIT_USER_NAME not set in .env-install"
    exit 1
fi

if [ -z "${GIT_USER_EMAIL:-}" ]; then
    log_error "GIT_USER_EMAIL not set in .env-install"
    exit 1
fi

TEMPLATE="${SCRIPT_DIR}/../git/.gitconfig"
TARGET="$HOME/.gitconfig"

if [ ! -f "$TEMPLATE" ]; then
    log_error "Template not found at $TEMPLATE"
    exit 1
fi

# Refuse to run if the template already carries an identity. That means a
# previous run wrote its output back into the repository, and continuing would
# compose identity on top of identity.
if grep -qE '^\[user\]' "$TEMPLATE"; then
    log_error "$TEMPLATE contains a [user] section; it should hold only shared settings."
    log_error "Restore it with: git checkout -- git/.gitconfig"
    exit 1
fi

# Back up the live config before replacing it.
if [ -f "$TARGET" ] && [ ! -L "$TARGET" ]; then
    backup="${TARGET}.backup.$(date +%Y%m%d_%H%M%S)"
    cp "$TARGET" "$backup" || {
        log_error "Failed to back up $TARGET"
        exit 1
    }
    log_info "Backed up existing config to $backup"
    prune_backups "$TARGET"
fi

if [ "${DRY_RUN:-0}" = "1" ]; then
    log_info "[dry-run] Would write $TARGET from $TEMPLATE plus [user] and signing settings"
    exit 0
fi

# Identity first, then the shared template verbatim.
{
    echo "# Generated by scripts/configure-git-user.sh from git/.gitconfig."
    echo "# Edit the template in the dotfiles repository, not this file."
    echo ""
    echo "[user]"
    echo "    name = ${GIT_USER_NAME}"
    echo "    email = ${GIT_USER_EMAIL}"

    if [ -n "${GIT_SIGNING_KEY:-}" ]; then
        echo "    signingkey = ${GIT_SIGNING_KEY}"
        echo ""
        echo "[commit]"
        echo "    gpgsign = true"
        echo ""
        echo "[tag]"
        echo "    gpgsign = true"
        echo ""
        echo "[gpg]"
        echo "    program = $(command -v gpg 2>/dev/null || echo gpg)"
    fi

    echo ""
    cat "$TEMPLATE"
} > "$TARGET"

chmod 644 "$TARGET"

if [ -n "${GIT_SIGNING_KEY:-}" ]; then
    log_info "GPG signing enabled with key ${GIT_SIGNING_KEY}"
else
    log_warn "GIT_SIGNING_KEY not set; commit signing is disabled"
    log_warn "Run ./setup-gpg-key.sh --import to record it in .env-install"
fi

log_info "Wrote $TARGET ($(grep -cE '^\s+[a-z-]+ = ' "$TARGET") settings)"
